### ISSUE TITLE
请问下插件的内部类如何加载？

### ISSUE THREAD

**Issue by jtyang** [simpleton/dalvik_patch#1]
你好：
我尝试用inject_secondary_dex这个项目去加载一个开源图片缓存Android-Universal-Image-Loader的jar转换成的dex，
执行完DexInjector.inject(dexInternalStoragePath.getAbsolutePath(),
                    defaultDexOptPath, defaultLibraryPath, this.className);
返回是true，可是代码执行到调用jar里面的内部类时却提示找不到，请问这是什么原因呢？Thanks！

java.lang.NoClassDefFoundError: com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder

**Comment by simpleton** [comment]
关于内部类，这里在5.0以下有一个坑，使用反射是无法fix的，需要自己修改加载时机和加载的内容来规避。不知你加载的时机是在哪里，反正近可能的早的去加非主的dex。

PS：可以给出你的代码和编译方法么？

**Comment by simpleton** [comment]
其实google在dx21里已经支持的多dex编译，建议还是用google的方案。

**Comment by jtyang** [comment]
好的，谢谢！
我看到百度云的客户端使用了这种插件加载机制，正好看到百度的那个dex合并的代码和你这个差不多，所以去尝试了下。
根据你的代码和反编译百度的代码，我写了个demo：http://pan.baidu.com/share/link?shareid=2604451231&uk=1979935982
运行时动态加载assets目录下的jar，调试后加载失败。（我是在eclipse的build 选项的 order and export那个选项不勾选编译时的universal-image-loader-1.9.0.jar打出的apk包）
对dex加载机制这块不熟悉，还望兄台有空的话不吝赐教，感激！

**Comment by simpleton** [comment]
这块其实是google搞的bug.现在基本已经修了。可以参照下这个：

https://developer.android.com/tools/building/multidex.html

只有项目要做插件框架才需要自己做inject dex.

**Comment by jtyang** [comment]
嗯，thanks！
